package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Campoformulario generated by hbm2java
 */
@Entity
@Table(name = "campoplantilla", schema = "public")
@org.hibernate.annotations.Entity(dynamicUpdate = true, selectBeforeUpdate = true)
public class Campoplantilla implements java.io.Serializable {

    private Long idCampo;
    private Formularioplantilla formularioplantilla;
    private CtgCatalogo ctgCatalogo;
    private String etiqueta;
    private String largocampo;
    private Boolean estado;

    public Campoplantilla() {
    }

    public Campoplantilla(Long idCampo) {
        this.idCampo = idCampo;
    }

    public Campoplantilla(Long idCampo, Formularioplantilla formularioplantilla, CtgCatalogo ctgCatalogo, String largocampo, Boolean estado) {
        this.idCampo = idCampo;
        this.formularioplantilla = formularioplantilla;
        this.ctgCatalogo = ctgCatalogo;
        this.largocampo = largocampo;
        this.estado = estado;
    }

    @Id
    @Column(name = "id_campo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IdGenerator")
    @SequenceGenerator(allocationSize = 1, name = "IdGenerator", sequenceName = "campoplantilla_id_seq")
    public Long getIdCampo() {
        return this.idCampo;
    }

    public void setIdCampo(Long idCampo) {
        this.idCampo = idCampo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_plantilla")
    public Formularioplantilla getFormularioplantilla() {
        return this.formularioplantilla;
    }

    public void setFormularioplantilla(Formularioplantilla formularioplantilla) {
        this.formularioplantilla = formularioplantilla;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }

    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    @Column(name = "largocampo", length = 100)
    public String getLargocampo() {
        return this.largocampo;
    }

    public void setLargocampo(String largocampo) {
        this.largocampo = largocampo;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the etiqueta
     */
    @Column(name = "etiqueta", length = 200)
    public String getEtiqueta() {
        return etiqueta;
    }

    /**
     * @param etiqueta the etiqueta to set
     */
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

}
