package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name="cita"
    ,schema="public"
)
public class Cita  implements java.io.Serializable {


     private int idCita;
     private Proceso proceso;
     private CtgCatalogo ctgCatalogo;
     private Date fecha;
     private String descripcion;
     private Set<Documentocita> documentocitas = new HashSet(0);
     private Set<Cobrocita> cobrocitas = new HashSet(0);

    public Cita() {
    }

	
    public Cita(int idCita) {
        this.idCita = idCita;
    }
    public Cita(int idCita, Proceso proceso, CtgCatalogo ctgCatalogo, Date fecha, String descripcion, Set<Documentocita> documentocitas, Set<Cobrocita> cobrocitas) {
       this.idCita = idCita;
       this.proceso = proceso;
       this.ctgCatalogo = ctgCatalogo;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.documentocitas = documentocitas;
       this.cobrocitas = cobrocitas;
    }
   
     @Id 

    
    @Column(name="id_cita", unique=true, nullable=false)
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso")
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }
    
    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cita")
    public Set<Documentocita> getDocumentocitas() {
        return this.documentocitas;
    }
    
    public void setDocumentocitas(Set<Documentocita> documentocitas) {
        this.documentocitas = documentocitas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cita")
    public Set<Cobrocita> getCobrocitas() {
        return this.cobrocitas;
    }
    
    public void setCobrocitas(Set<Cobrocita> cobrocitas) {
        this.cobrocitas = cobrocitas;
    }




}


