package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cobrocita generated by hbm2java
 */
@Entity
@Table(name="cobrocita"
    ,schema="public"
)
public class Cobrocita  implements java.io.Serializable {


     private int idCobrocita;
     private Cita cita;
     private Cobro cobro;

    public Cobrocita() {
    }

	
    public Cobrocita(int idCobrocita) {
        this.idCobrocita = idCobrocita;
    }
    public Cobrocita(int idCobrocita, Cita cita, Cobro cobro) {
       this.idCobrocita = idCobrocita;
       this.cita = cita;
       this.cobro = cobro;
    }
   
     @Id 

    
    @Column(name="id_cobrocita", unique=true, nullable=false)
    public int getIdCobrocita() {
        return this.idCobrocita;
    }
    
    public void setIdCobrocita(int idCobrocita) {
        this.idCobrocita = idCobrocita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cita")
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cobro")
    public Cobro getCobro() {
        return this.cobro;
    }
    
    public void setCobro(Cobro cobro) {
        this.cobro = cobro;
    }




}


