package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cobro generated by hbm2java
 */
@Entity
@Table(name="cobro"
    ,schema="public"
)
public class Cobro  implements java.io.Serializable {


     private int idCobro;
     private CtgCatalogo ctgCatalogo;
     private String monto;
     private Date fechaingreso;
     private boolean estado;
     private Set<Cobroaudiencia> cobroaudiencias = new HashSet(0);
     private Set<Cobrosubaudiencia> cobrosubaudiencias = new HashSet(0);
     private Set<Cobrocita> cobrocitas = new HashSet(0);
     private Set<Pago> pagos = new HashSet(0);

    public Cobro() {
    }

	
    public Cobro(int idCobro, String monto, Date fechaingreso, boolean estado) {
        this.idCobro = idCobro;
        this.monto = monto;
        this.fechaingreso = fechaingreso;
        this.estado = estado;
    }
    public Cobro(int idCobro, CtgCatalogo ctgCatalogo, String monto, Date fechaingreso, boolean estado, Set<Cobroaudiencia> cobroaudiencias, Set<Cobrosubaudiencia> cobrosubaudiencias, Set<Cobrocita> cobrocitas, Set<Pago> pagos) {
       this.idCobro = idCobro;
       this.ctgCatalogo = ctgCatalogo;
       this.monto = monto;
       this.fechaingreso = fechaingreso;
       this.estado = estado;
       this.cobroaudiencias = cobroaudiencias;
       this.cobrosubaudiencias = cobrosubaudiencias;
       this.cobrocitas = cobrocitas;
       this.pagos = pagos;
    }
   
     @Id 

    
    @Column(name="id_cobro", unique=true, nullable=false)
    public int getIdCobro() {
        return this.idCobro;
    }
    
    public void setIdCobro(int idCobro) {
        this.idCobro = idCobro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }
    
    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    
    @Column(name="monto", nullable=false, length=50)
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaingreso", nullable=false, length=13)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cobro")
    public Set<Cobroaudiencia> getCobroaudiencias() {
        return this.cobroaudiencias;
    }
    
    public void setCobroaudiencias(Set<Cobroaudiencia> cobroaudiencias) {
        this.cobroaudiencias = cobroaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cobro")
    public Set<Cobrosubaudiencia> getCobrosubaudiencias() {
        return this.cobrosubaudiencias;
    }
    
    public void setCobrosubaudiencias(Set<Cobrosubaudiencia> cobrosubaudiencias) {
        this.cobrosubaudiencias = cobrosubaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cobro")
    public Set<Cobrocita> getCobrocitas() {
        return this.cobrocitas;
    }
    
    public void setCobrocitas(Set<Cobrocita> cobrocitas) {
        this.cobrocitas = cobrocitas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cobro")
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


