package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccioncliente generated by hbm2java
 */
@Entity
@Table(name="direccioncliente"
    ,schema="public"
)
public class Direccioncliente  implements java.io.Serializable {


     private DireccionclienteId id;
     private Direccion direccion;
     private Cliente cliente;

    public Direccioncliente() {
    }

	
    public Direccioncliente(DireccionclienteId id) {
        this.id = id;
    }
    public Direccioncliente(DireccionclienteId id, Direccion direccion, Cliente cliente) {
       this.id = id;
       this.direccion = direccion;
       this.cliente = cliente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDireccion", column=@Column(name="id_direccion") ), 
        @AttributeOverride(name="idCliente", column=@Column(name="id_cliente") ) } )
    public DireccionclienteId getId() {
        return this.id;
    }
    
    public void setId(DireccionclienteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_direccion", insertable=false, updatable=false)
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", insertable=false, updatable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


