package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccioncontacto generated by hbm2java
 */
@Entity
@Table(name="direccioncontacto"
    ,schema="public"
)
public class Direccioncontacto  implements java.io.Serializable {


     private int idDircontaco;
     private Contacto contacto;
     private Direccion direccion;

    public Direccioncontacto() {
    }

	
    public Direccioncontacto(int idDircontaco) {
        this.idDircontaco = idDircontaco;
    }
    public Direccioncontacto(int idDircontaco, Contacto contacto, Direccion direccion) {
       this.idDircontaco = idDircontaco;
       this.contacto = contacto;
       this.direccion = direccion;
    }
   
     @Id 

    
    @Column(name="id_dircontaco", unique=true, nullable=false)
    public int getIdDircontaco() {
        return this.idDircontaco;
    }
    
    public void setIdDircontaco(int idDircontaco) {
        this.idDircontaco = idDircontaco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contacto")
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_direccion")
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }




}


