package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Documentosubaudi generated by hbm2java
 */
@Entity
@Table(name="documentosubaudi"
    ,schema="public"
)
public class Documentosubaudi  implements java.io.Serializable {


     private int idDocsubaud;
     private Documento documento;
     private Subaudiencia subaudiencia;

    public Documentosubaudi() {
    }

	
    public Documentosubaudi(int idDocsubaud, Documento documento) {
        this.idDocsubaud = idDocsubaud;
        this.documento = documento;
    }
    public Documentosubaudi(int idDocsubaud, Documento documento, Subaudiencia subaudiencia) {
       this.idDocsubaud = idDocsubaud;
       this.documento = documento;
       this.subaudiencia = subaudiencia;
    }
   
     @Id 

    
    @Column(name="id_docsubaud", unique=true, nullable=false)
    public int getIdDocsubaud() {
        return this.idDocsubaud;
    }
    
    public void setIdDocsubaud(int idDocsubaud) {
        this.idDocsubaud = idDocsubaud;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_documento", nullable=false)
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_subaudiencia")
    public Subaudiencia getSubaudiencia() {
        return this.subaudiencia;
    }
    
    public void setSubaudiencia(Subaudiencia subaudiencia) {
        this.subaudiencia = subaudiencia;
    }




}


