package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Juzgado generated by hbm2java
 */
@Entity
@Table(name="juzgado"
    ,schema="public"
)
public class Juzgado  implements java.io.Serializable {


     private int idJuzgado;
     private String nombre;
     private String direccion;
     private Set<Contacto> contactos = new HashSet(0);
     private Set<Subaudiencia> subaudiencias = new HashSet(0);
     private Set<Titular> titulars = new HashSet(0);
     private Set<Audiencia> audiencias = new HashSet(0);

    public Juzgado() {
    }

	
    public Juzgado(int idJuzgado) {
        this.idJuzgado = idJuzgado;
    }
    public Juzgado(int idJuzgado, String nombre, String direccion, Set<Contacto> contactos, Set<Subaudiencia> subaudiencias, Set<Titular> titulars, Set<Audiencia> audiencias) {
       this.idJuzgado = idJuzgado;
       this.nombre = nombre;
       this.direccion = direccion;
       this.contactos = contactos;
       this.subaudiencias = subaudiencias;
       this.titulars = titulars;
       this.audiencias = audiencias;
    }
   
     @Id 

    
    @Column(name="id_juzgado", unique=true, nullable=false)
    public int getIdJuzgado() {
        return this.idJuzgado;
    }
    
    public void setIdJuzgado(int idJuzgado) {
        this.idJuzgado = idJuzgado;
    }

    
    @Column(name="nombre", length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", length=250)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="juzgado")
    public Set<Contacto> getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set<Contacto> contactos) {
        this.contactos = contactos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="juzgado")
    public Set<Subaudiencia> getSubaudiencias() {
        return this.subaudiencias;
    }
    
    public void setSubaudiencias(Set<Subaudiencia> subaudiencias) {
        this.subaudiencias = subaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="juzgado")
    public Set<Titular> getTitulars() {
        return this.titulars;
    }
    
    public void setTitulars(Set<Titular> titulars) {
        this.titulars = titulars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="juzgado")
    public Set<Audiencia> getAudiencias() {
        return this.audiencias;
    }
    
    public void setAudiencias(Set<Audiencia> audiencias) {
        this.audiencias = audiencias;
    }




}


