package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="public"
)
public class Pais  implements java.io.Serializable {


     private int idPais;
     private String nombrepais;
     private Boolean estado;
     private Set<Departamento> departamentos = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idPais) {
        this.idPais = idPais;
    }
    public Pais(int idPais, String nombrepais, Boolean estado, Set<Departamento> departamentos) {
       this.idPais = idPais;
       this.nombrepais = nombrepais;
       this.estado = estado;
       this.departamentos = departamentos;
    }
   
     @Id 

    
    @Column(name="id_pais", unique=true, nullable=false)
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="nombrepais", length=50)
    public String getNombrepais() {
        return this.nombrepais;
    }
    
    public void setNombrepais(String nombrepais) {
        this.nombrepais = nombrepais;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


