package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name="proceso"
    ,schema="public"
)
public class Proceso  implements java.io.Serializable {


     private Long idProceso;
     private Cliente cliente;
     private String nombre;
     private String codigo;
     private String descripcion;
     private String fechaRegistro;
     private Set<Usuarioproceso> usuarioprocesos = new HashSet(0);
     private Set<Formularioproceso> formularioprocesos = new HashSet(0);
     private Set<Audiencia> audiencias = new HashSet(0);
     private Set<Cita> citas = new HashSet(0);

    public Proceso() {
    }

	
    public Proceso(Long idProceso) {
        this.idProceso = idProceso;
    }
    public Proceso(Long idProceso, Cliente cliente, String nombre, String codigo, String descripcion, String fechaRegistro, Set<Usuarioproceso> usuarioprocesos, Set<Formularioproceso> formularioprocesos, Set<Audiencia> audiencias, Set<Cita> citas) {
       this.idProceso = idProceso;
       this.cliente = cliente;
       this.nombre = nombre;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.usuarioprocesos = usuarioprocesos;
       this.formularioprocesos = formularioprocesos;
       this.audiencias = audiencias;
       this.citas = citas;
    }
   
    @Id 
    @Column(name="id_proceso", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IdGenerator")
    @SequenceGenerator(allocationSize = 1, name = "IdGenerator", sequenceName = "proceso_id_seq")
    public Long getIdProceso() {
        return this.idProceso;
    }
    
    public void setIdProceso(Long idProceso) {
        this.idProceso = idProceso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="codigo", length=20)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="fecha_registro", length=15)
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proceso")
    public Set<Usuarioproceso> getUsuarioprocesos() {
        return this.usuarioprocesos;
    }
    
    public void setUsuarioprocesos(Set<Usuarioproceso> usuarioprocesos) {
        this.usuarioprocesos = usuarioprocesos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proceso")
    public Set<Formularioproceso> getFormularioprocesos() {
        return this.formularioprocesos;
    }
    
    public void setFormularioprocesos(Set<Formularioproceso> formularioprocesos) {
        this.formularioprocesos = formularioprocesos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proceso")
    public Set<Audiencia> getAudiencias() {
        return this.audiencias;
    }
    
    public void setAudiencias(Set<Audiencia> audiencias) {
        this.audiencias = audiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proceso")
    public Set<Cita> getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set<Cita> citas) {
        this.citas = citas;
    }




}


