package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefonocontacto generated by hbm2java
 */
@Entity
@Table(name="telefonocontacto"
    ,schema="public"
)
public class Telefonocontacto  implements java.io.Serializable {


     private int idTelecontac;
     private Contacto contacto;
     private Telefono telefono;

    public Telefonocontacto() {
    }

	
    public Telefonocontacto(int idTelecontac) {
        this.idTelecontac = idTelecontac;
    }
    public Telefonocontacto(int idTelecontac, Contacto contacto, Telefono telefono) {
       this.idTelecontac = idTelecontac;
       this.contacto = contacto;
       this.telefono = telefono;
    }
   
     @Id 

    
    @Column(name="id_telecontac", unique=true, nullable=false)
    public int getIdTelecontac() {
        return this.idTelecontac;
    }
    
    public void setIdTelecontac(int idTelecontac) {
        this.idTelecontac = idTelecontac;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_contacto")
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_telefono")
    public Telefono getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Telefono telefono) {
        this.telefono = telefono;
    }




}


