package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testigo generated by hbm2java
 */
@Entity
@Table(name="testigo"
    ,schema="public"
)
public class Testigo  implements java.io.Serializable {


     private int idTestigo;
     private String nombre;
     private Integer edad;
     private String nacionalidad;
     private String fechaCita;
     private Set<Testigoaudiencia> testigoaudiencias = new HashSet(0);
     private Set<Testigosubaudiencia> testigosubaudiencias = new HashSet(0);

    public Testigo() {
    }

	
    public Testigo(int idTestigo) {
        this.idTestigo = idTestigo;
    }
    public Testigo(int idTestigo, String nombre, Integer edad, String nacionalidad, String fechaCita, Set<Testigoaudiencia> testigoaudiencias, Set<Testigosubaudiencia> testigosubaudiencias) {
       this.idTestigo = idTestigo;
       this.nombre = nombre;
       this.edad = edad;
       this.nacionalidad = nacionalidad;
       this.fechaCita = fechaCita;
       this.testigoaudiencias = testigoaudiencias;
       this.testigosubaudiencias = testigosubaudiencias;
    }
   
     @Id 

    
    @Column(name="id_testigo", unique=true, nullable=false)
    public int getIdTestigo() {
        return this.idTestigo;
    }
    
    public void setIdTestigo(int idTestigo) {
        this.idTestigo = idTestigo;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    
    @Column(name="nacionalidad", length=20)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="fecha_cita", length=15)
    public String getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(String fechaCita) {
        this.fechaCita = fechaCita;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testigo")
    public Set<Testigoaudiencia> getTestigoaudiencias() {
        return this.testigoaudiencias;
    }
    
    public void setTestigoaudiencias(Set<Testigoaudiencia> testigoaudiencias) {
        this.testigoaudiencias = testigoaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testigo")
    public Set<Testigosubaudiencia> getTestigosubaudiencias() {
        return this.testigosubaudiencias;
    }
    
    public void setTestigosubaudiencias(Set<Testigosubaudiencia> testigosubaudiencias) {
        this.testigosubaudiencias = testigosubaudiencias;
    }




}


