package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private Long idUsuario;
     private CtgCatalogo ctgCatalogo;
     private String usuario;
     private String password;
     private Boolean estado;
     private String nombre;
     private String apellido;
     private String cambiarClave;
     private Set<Usuarioproceso> usuarioprocesos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Long idUsuario, CtgCatalogo ctgCatalogo) {
        this.idUsuario = idUsuario;
        this.ctgCatalogo = ctgCatalogo;
    }
    public Usuario(Long idUsuario, CtgCatalogo ctgCatalogo, String usuario, String password, Boolean estado, String nombre, String apellido, String cambiarClave, Set<Usuarioproceso> usuarioprocesos) {
       this.idUsuario = idUsuario;
       this.ctgCatalogo = ctgCatalogo;
       this.usuario = usuario;
       this.password = password;
       this.estado = estado;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cambiarClave = cambiarClave;
       this.usuarioprocesos = usuarioprocesos;
    }
    
    @Id
    @Column(name="id_usuario", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IdGenerator")
    @SequenceGenerator(allocationSize = 1, name = "IdGenerator", sequenceName = "USUARIO_ID_SEQ")
  
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ctg_cat_id", nullable=false)
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }
    
    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    
    @Column(name="usuario", length=20)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", length=2000)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=100)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="cambiar_clave", length=2)
    public String getCambiarClave() {
        return this.cambiarClave;
    }
    
    public void setCambiarClave(String cambiarClave) {
        this.cambiarClave = cambiarClave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Usuarioproceso> getUsuarioprocesos() {
        return this.usuarioprocesos;
    }
    
    public void setUsuarioprocesos(Set<Usuarioproceso> usuarioprocesos) {
        this.usuarioprocesos = usuarioprocesos;
    }




}


