
package com.ars.sirproj.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSConsultaSirproj", targetNamespace = "http://ws.sirproj.ars.com/", wsdlLocation = "file:/C:/Users/bms641/Desktop/clienteWS/WSConsultaSirproj.wsdl")
public class WSConsultaSirproj
    extends Service
{

    private final static URL WSCONSULTASIRPROJ_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTASIRPROJ_EXCEPTION;
    private final static QName WSCONSULTASIRPROJ_QNAME = new QName("http://ws.sirproj.ars.com/", "WSConsultaSirproj");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/bms641/Desktop/clienteWS/WSConsultaSirproj.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTASIRPROJ_WSDL_LOCATION = url;
        WSCONSULTASIRPROJ_EXCEPTION = e;
    }

    public WSConsultaSirproj() {
        super(__getWsdlLocation(), WSCONSULTASIRPROJ_QNAME);
    }

    public WSConsultaSirproj(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTASIRPROJ_QNAME, features);
    }

    public WSConsultaSirproj(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTASIRPROJ_QNAME);
    }

    public WSConsultaSirproj(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTASIRPROJ_QNAME, features);
    }

    public WSConsultaSirproj(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSConsultaSirproj(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSConsultaSirprojService
     */
    @WebEndpoint(name = "WSConsultaSirprojPort")
    public WSConsultaSirprojService getWSConsultaSirprojPort() {
        return super.getPort(new QName("http://ws.sirproj.ars.com/", "WSConsultaSirprojPort"), WSConsultaSirprojService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSConsultaSirprojService
     */
    @WebEndpoint(name = "WSConsultaSirprojPort")
    public WSConsultaSirprojService getWSConsultaSirprojPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sirproj.ars.com/", "WSConsultaSirprojPort"), WSConsultaSirprojService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTASIRPROJ_EXCEPTION!= null) {
            throw WSCONSULTASIRPROJ_EXCEPTION;
        }
        return WSCONSULTASIRPROJ_WSDL_LOCATION;
    }

}
