package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Audiencia generated by hbm2java
 */
@Entity
@Table(name="audiencia"
    ,schema="public"
)
public class Audiencia  implements java.io.Serializable {


     private int idAudiencia;
     private Juzgado juzgado;
     private Proceso proceso;
     private Date fecha;
     private String sentencia;
     private String apelaciones;
     private String recursos;
     private String descripcion;
     private Set<Cobroaudiencia> cobroaudiencias = new HashSet(0);
     private Set<Testigoaudiencia> testigoaudiencias = new HashSet(0);
     private Set<Documentoaudiencia> documentoaudiencias = new HashSet(0);
     private Set<Subaudiencia> subaudiencias = new HashSet(0);

    public Audiencia() {
    }

	
    public Audiencia(int idAudiencia) {
        this.idAudiencia = idAudiencia;
    }
    public Audiencia(int idAudiencia, Juzgado juzgado, Proceso proceso, Date fecha, String sentencia, String apelaciones, String recursos, String descripcion, Set<Cobroaudiencia> cobroaudiencias, Set<Testigoaudiencia> testigoaudiencias, Set<Documentoaudiencia> documentoaudiencias, Set<Subaudiencia> subaudiencias) {
       this.idAudiencia = idAudiencia;
       this.juzgado = juzgado;
       this.proceso = proceso;
       this.fecha = fecha;
       this.sentencia = sentencia;
       this.apelaciones = apelaciones;
       this.recursos = recursos;
       this.descripcion = descripcion;
       this.cobroaudiencias = cobroaudiencias;
       this.testigoaudiencias = testigoaudiencias;
       this.documentoaudiencias = documentoaudiencias;
       this.subaudiencias = subaudiencias;
    }
   
     @Id 

    
    @Column(name="id_audiencia", unique=true, nullable=false)
    public int getIdAudiencia() {
        return this.idAudiencia;
    }
    
    public void setIdAudiencia(int idAudiencia) {
        this.idAudiencia = idAudiencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_juzgado")
    public Juzgado getJuzgado() {
        return this.juzgado;
    }
    
    public void setJuzgado(Juzgado juzgado) {
        this.juzgado = juzgado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso")
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="sentencia", length=250)
    public String getSentencia() {
        return this.sentencia;
    }
    
    public void setSentencia(String sentencia) {
        this.sentencia = sentencia;
    }

    
    @Column(name="apelaciones", length=250)
    public String getApelaciones() {
        return this.apelaciones;
    }
    
    public void setApelaciones(String apelaciones) {
        this.apelaciones = apelaciones;
    }

    
    @Column(name="recursos", length=250)
    public String getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(String recursos) {
        this.recursos = recursos;
    }

    
    @Column(name="descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="audiencia")
    public Set<Cobroaudiencia> getCobroaudiencias() {
        return this.cobroaudiencias;
    }
    
    public void setCobroaudiencias(Set<Cobroaudiencia> cobroaudiencias) {
        this.cobroaudiencias = cobroaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="audiencia")
    public Set<Testigoaudiencia> getTestigoaudiencias() {
        return this.testigoaudiencias;
    }
    
    public void setTestigoaudiencias(Set<Testigoaudiencia> testigoaudiencias) {
        this.testigoaudiencias = testigoaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="audiencia")
    public Set<Documentoaudiencia> getDocumentoaudiencias() {
        return this.documentoaudiencias;
    }
    
    public void setDocumentoaudiencias(Set<Documentoaudiencia> documentoaudiencias) {
        this.documentoaudiencias = documentoaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="audiencia")
    public Set<Subaudiencia> getSubaudiencias() {
        return this.subaudiencias;
    }
    
    public void setSubaudiencias(Set<Subaudiencia> subaudiencias) {
        this.subaudiencias = subaudiencias;
    }




}


