package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Campoformulario generated by hbm2java
 */
@Entity
@Table(name = "campoformulario", schema = "public")
@org.hibernate.annotations.Entity(dynamicUpdate = true, selectBeforeUpdate = true)
public class Campoformulario implements java.io.Serializable {

    private Long idCampo;
    private Formularioproceso formularioproceso;
    private CtgCatalogo ctgCatalogo;
    private String valorcampo;
    private String largocampo;
    private Boolean estado;
    private String etiqueta;

    public Campoformulario() {
    }

    public Campoformulario(Long idCampo) {
        this.idCampo = idCampo;
    }

    public Campoformulario(Long idCampo, Formularioproceso formularioproceso, CtgCatalogo ctgCatalogo, String valorcampo, String largocampo, Boolean estado) {
        this.idCampo = idCampo;
        this.formularioproceso = formularioproceso;
        this.ctgCatalogo = ctgCatalogo;
        this.valorcampo = valorcampo;
        this.largocampo = largocampo;
        this.estado = estado;
    }

    @Id
    @Column(name = "id_campo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "IdGenerator")
    @SequenceGenerator(allocationSize = 1, name = "IdGenerator", sequenceName = "campoformulario_id_seq")
    public Long getIdCampo() {
        return this.idCampo;
    }

    public void setIdCampo(Long idCampo) {
        this.idCampo = idCampo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_formulario")
    public Formularioproceso getFormularioproceso() {
        return this.formularioproceso;
    }

    public void setFormularioproceso(Formularioproceso formularioproceso) {
        this.formularioproceso = formularioproceso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }

    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    @Column(name = "valorcampo", length = 250)
    public String getValorcampo() {
        return this.valorcampo;
    }

    public void setValorcampo(String valorcampo) {
        this.valorcampo = valorcampo;
    }

    @Column(name = "largocampo", length = 100)
    public String getLargocampo() {
        return this.largocampo;
    }

    public void setLargocampo(String largocampo) {
        this.largocampo = largocampo;
    }

    @Column(name = "estado")
    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the etiqueta
     */
     @Column(name = "etiqueta", length = 200)
    public String getEtiqueta() {
        return etiqueta;
    }

    /**
     * @param etiqueta the etiqueta to set
     */
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

}
