package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,schema="public"
)
public class Compra  implements java.io.Serializable {


     private int idCompra;
     private String descripcion;
     private String fechaCompra;
     private String numCompra;
     private Set<Listaproducto> listaproductos = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int idCompra) {
        this.idCompra = idCompra;
    }
    public Compra(int idCompra, String descripcion, String fechaCompra, String numCompra, Set<Listaproducto> listaproductos) {
       this.idCompra = idCompra;
       this.descripcion = descripcion;
       this.fechaCompra = fechaCompra;
       this.numCompra = numCompra;
       this.listaproductos = listaproductos;
    }
   
     @Id 

    
    @Column(name="id__compra", unique=true, nullable=false)
    public int getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(int idCompra) {
        this.idCompra = idCompra;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="fecha_compra", length=50)
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    
    @Column(name="num_compra", length=50)
    public String getNumCompra() {
        return this.numCompra;
    }
    
    public void setNumCompra(String numCompra) {
        this.numCompra = numCompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compra")
    public Set<Listaproducto> getListaproductos() {
        return this.listaproductos;
    }
    
    public void setListaproductos(Set<Listaproducto> listaproductos) {
        this.listaproductos = listaproductos;
    }




}


