package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CtgCatalogo generated by hbm2java
 */
@Entity
@Table(name="ctg_catalogo"
    ,schema="public"
)
public class CtgCatalogo  implements java.io.Serializable {


     private int ctgCatId;
     private String ctgCatActivo;
     private String ctgCatHijo;
     private String ctgCatNombre;
     private String ctgCatPadre;
     private String ctgCatDetallar;
     private Set<Ocupacion> ocupacions = new HashSet(0);
     private Set<Campoformulario> campoformularios = new HashSet(0);
     private Set<Documento> documentos = new HashSet(0);
     private Set<Cita> citas = new HashSet(0);
     private Set<Cobro> cobros = new HashSet(0);
     private Set<Usuario> usuarios = new HashSet(0);

    public CtgCatalogo() {
    }

	
    public CtgCatalogo(int ctgCatId) {
        this.ctgCatId = ctgCatId;
    }
    public CtgCatalogo(int ctgCatId, String ctgCatActivo, String ctgCatHijo, String ctgCatNombre, String ctgCatPadre, String ctgCatDetallar, Set<Ocupacion> ocupacions, Set<Campoformulario> campoformularios, Set<Documento> documentos, Set<Cita> citas, Set<Cobro> cobros, Set<Usuario> usuarios) {
       this.ctgCatId = ctgCatId;
       this.ctgCatActivo = ctgCatActivo;
       this.ctgCatHijo = ctgCatHijo;
       this.ctgCatNombre = ctgCatNombre;
       this.ctgCatPadre = ctgCatPadre;
       this.ctgCatDetallar = ctgCatDetallar;
       this.ocupacions = ocupacions;
       this.campoformularios = campoformularios;
       this.documentos = documentos;
       this.citas = citas;
       this.cobros = cobros;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="ctg_cat_id", unique=true, nullable=false)
    public int getCtgCatId() {
        return this.ctgCatId;
    }
    
    public void setCtgCatId(int ctgCatId) {
        this.ctgCatId = ctgCatId;
    }

    
    @Column(name="ctg_cat_activo", length=1)
    public String getCtgCatActivo() {
        return this.ctgCatActivo;
    }
    
    public void setCtgCatActivo(String ctgCatActivo) {
        this.ctgCatActivo = ctgCatActivo;
    }

    
    @Column(name="ctg_cat_hijo", length=5)
    public String getCtgCatHijo() {
        return this.ctgCatHijo;
    }
    
    public void setCtgCatHijo(String ctgCatHijo) {
        this.ctgCatHijo = ctgCatHijo;
    }

    
    @Column(name="ctg_cat_nombre", length=100)
    public String getCtgCatNombre() {
        return this.ctgCatNombre;
    }
    
    public void setCtgCatNombre(String ctgCatNombre) {
        this.ctgCatNombre = ctgCatNombre;
    }

    
    @Column(name="ctg_cat_padre", length=5)
    public String getCtgCatPadre() {
        return this.ctgCatPadre;
    }
    
    public void setCtgCatPadre(String ctgCatPadre) {
        this.ctgCatPadre = ctgCatPadre;
    }

    
    @Column(name="ctg_cat_detallar", length=1)
    public String getCtgCatDetallar() {
        return this.ctgCatDetallar;
    }
    
    public void setCtgCatDetallar(String ctgCatDetallar) {
        this.ctgCatDetallar = ctgCatDetallar;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Ocupacion> getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set<Ocupacion> ocupacions) {
        this.ocupacions = ocupacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Campoformulario> getCampoformularios() {
        return this.campoformularios;
    }
    
    public void setCampoformularios(Set<Campoformulario> campoformularios) {
        this.campoformularios = campoformularios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Documento> getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set<Documento> documentos) {
        this.documentos = documentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Cita> getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set<Cita> citas) {
        this.citas = citas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Cobro> getCobros() {
        return this.cobros;
    }
    
    public void setCobros(Set<Cobro> cobros) {
        this.cobros = cobros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgCatalogo")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


