package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,schema="public"
)
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private Pais pais;
     private String nombredepto;
     private Boolean estado;
     private Set<Municipio> municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(int idDepartamento, Pais pais, String nombredepto, Boolean estado, Set<Municipio> municipios) {
       this.idDepartamento = idDepartamento;
       this.pais = pais;
       this.nombredepto = nombredepto;
       this.estado = estado;
       this.municipios = municipios;
    }
   
     @Id 

    
    @Column(name="id_departamento", unique=true, nullable=false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pais")
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="nombredepto", length=100)
    public String getNombredepto() {
        return this.nombredepto;
    }
    
    public void setNombredepto(String nombredepto) {
        this.nombredepto = nombredepto;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Municipio> getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set<Municipio> municipios) {
        this.municipios = municipios;
    }




}


