package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name="documento"
    ,schema="public"
)
public class Documento  implements java.io.Serializable {


     private int idDocumento;
     private CtgCatalogo ctgCatalogo;
     private Integer url;
     private Boolean estado;
     private Set<Documentoaudiencia> documentoaudiencias = new HashSet(0);
     private Set<Documentosubaudi> documentosubaudis = new HashSet(0);
     private Set<Documentocita> documentocitas = new HashSet(0);

    public Documento() {
    }

	
    public Documento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Documento(int idDocumento, CtgCatalogo ctgCatalogo, Integer url, Boolean estado, Set<Documentoaudiencia> documentoaudiencias, Set<Documentosubaudi> documentosubaudis, Set<Documentocita> documentocitas) {
       this.idDocumento = idDocumento;
       this.ctgCatalogo = ctgCatalogo;
       this.url = url;
       this.estado = estado;
       this.documentoaudiencias = documentoaudiencias;
       this.documentosubaudis = documentosubaudis;
       this.documentocitas = documentocitas;
    }
   
     @Id 

    
    @Column(name="id_documento", unique=true, nullable=false)
    public int getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(int idDocumento) {
        this.idDocumento = idDocumento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }
    
    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    
    @Column(name="url")
    public Integer getUrl() {
        return this.url;
    }
    
    public void setUrl(Integer url) {
        this.url = url;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documento")
    public Set<Documentoaudiencia> getDocumentoaudiencias() {
        return this.documentoaudiencias;
    }
    
    public void setDocumentoaudiencias(Set<Documentoaudiencia> documentoaudiencias) {
        this.documentoaudiencias = documentoaudiencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documento")
    public Set<Documentosubaudi> getDocumentosubaudis() {
        return this.documentosubaudis;
    }
    
    public void setDocumentosubaudis(Set<Documentosubaudi> documentosubaudis) {
        this.documentosubaudis = documentosubaudis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documento")
    public Set<Documentocita> getDocumentocitas() {
        return this.documentocitas;
    }
    
    public void setDocumentocitas(Set<Documentocita> documentocitas) {
        this.documentocitas = documentocitas;
    }




}


