package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formularioproceso generated by hbm2java
 */
@Entity
@Table(name="formularioproceso"
    ,schema="public"
)
public class Formularioproceso  implements java.io.Serializable {


     private int idFormulario;
     private Proceso proceso;
     private Boolean estado;
     private Set<Campoformulario> campoformularios = new HashSet(0);

    public Formularioproceso() {
    }

	
    public Formularioproceso(int idFormulario) {
        this.idFormulario = idFormulario;
    }
    public Formularioproceso(int idFormulario, Proceso proceso, Boolean estado, Set<Campoformulario> campoformularios) {
       this.idFormulario = idFormulario;
       this.proceso = proceso;
       this.estado = estado;
       this.campoformularios = campoformularios;
    }
   
     @Id 

    
    @Column(name="id_formulario", unique=true, nullable=false)
    public int getIdFormulario() {
        return this.idFormulario;
    }
    
    public void setIdFormulario(int idFormulario) {
        this.idFormulario = idFormulario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proceso")
    public Proceso getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Proceso proceso) {
        this.proceso = proceso;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formularioproceso")
    public Set<Campoformulario> getCampoformularios() {
        return this.campoformularios;
    }
    
    public void setCampoformularios(Set<Campoformulario> campoformularios) {
        this.campoformularios = campoformularios;
    }




}


