package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="municipio"
    ,schema="public"
)
public class Municipio  implements java.io.Serializable {


     private int idMunicipio;
     private Departamento departamento;
     private String nombremunici;
     private Boolean estado;
     private Set<Direccion> direccions = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Municipio(int idMunicipio, Departamento departamento, String nombremunici, Boolean estado, Set<Direccion> direccions) {
       this.idMunicipio = idMunicipio;
       this.departamento = departamento;
       this.nombremunici = nombremunici;
       this.estado = estado;
       this.direccions = direccions;
    }
   
     @Id 

    
    @Column(name="id_municipio", unique=true, nullable=false)
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_departamento")
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="nombremunici", length=100)
    public String getNombremunici() {
        return this.nombremunici;
    }
    
    public void setNombremunici(String nombremunici) {
        this.nombremunici = nombremunici;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


