package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ocupacion generated by hbm2java
 */
@Entity
@Table(name="ocupacion"
    ,schema="public"
)
public class Ocupacion  implements java.io.Serializable {


     private int idOcupacion;
     private CtgCatalogo ctgCatalogo;
     private String descripcionocupacion;
     private Boolean activo;
     private Set<Cliente> clientes = new HashSet(0);

    public Ocupacion() {
    }

	
    public Ocupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public Ocupacion(int idOcupacion, CtgCatalogo ctgCatalogo, String descripcionocupacion, Boolean activo, Set<Cliente> clientes) {
       this.idOcupacion = idOcupacion;
       this.ctgCatalogo = ctgCatalogo;
       this.descripcionocupacion = descripcionocupacion;
       this.activo = activo;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="id_ocupacion", unique=true, nullable=false)
    public int getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ctg_cat_id")
    public CtgCatalogo getCtgCatalogo() {
        return this.ctgCatalogo;
    }
    
    public void setCtgCatalogo(CtgCatalogo ctgCatalogo) {
        this.ctgCatalogo = ctgCatalogo;
    }

    
    @Column(name="descripcionocupacion", length=50)
    public String getDescripcionocupacion() {
        return this.descripcionocupacion;
    }
    
    public void setDescripcionocupacion(String descripcionocupacion) {
        this.descripcionocupacion = descripcionocupacion;
    }

    
    @Column(name="activo")
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ocupacion")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


