package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="pago"
    ,schema="public"
)
public class Pago  implements java.io.Serializable {


     private int idPago;
     private Cobro cobro;
     private String monto;
     private Date fechaingreso;

    public Pago() {
    }

	
    public Pago(int idPago, String monto, Date fechaingreso) {
        this.idPago = idPago;
        this.monto = monto;
        this.fechaingreso = fechaingreso;
    }
    public Pago(int idPago, Cobro cobro, String monto, Date fechaingreso) {
       this.idPago = idPago;
       this.cobro = cobro;
       this.monto = monto;
       this.fechaingreso = fechaingreso;
    }
   
     @Id 

    
    @Column(name="id_pago", unique=true, nullable=false)
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cobro")
    public Cobro getCobro() {
        return this.cobro;
    }
    
    public void setCobro(Cobro cobro) {
        this.cobro = cobro;
    }

    
    @Column(name="monto", nullable=false, length=50)
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaingreso", nullable=false, length=13)
    public Date getFechaingreso() {
        return this.fechaingreso;
    }
    
    public void setFechaingreso(Date fechaingreso) {
        this.fechaingreso = fechaingreso;
    }




}


