package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Testigoaudiencia generated by hbm2java
 */
@Entity
@Table(name="testigoaudiencia"
    ,schema="public"
)
public class Testigoaudiencia  implements java.io.Serializable {


     private int idTestigoaudien;
     private Audiencia audiencia;
     private Testigo testigo;

    public Testigoaudiencia() {
    }

	
    public Testigoaudiencia(int idTestigoaudien) {
        this.idTestigoaudien = idTestigoaudien;
    }
    public Testigoaudiencia(int idTestigoaudien, Audiencia audiencia, Testigo testigo) {
       this.idTestigoaudien = idTestigoaudien;
       this.audiencia = audiencia;
       this.testigo = testigo;
    }
   
     @Id 

    
    @Column(name="id_testigoaudien", unique=true, nullable=false)
    public int getIdTestigoaudien() {
        return this.idTestigoaudien;
    }
    
    public void setIdTestigoaudien(int idTestigoaudien) {
        this.idTestigoaudien = idTestigoaudien;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_audiencia")
    public Audiencia getAudiencia() {
        return this.audiencia;
    }
    
    public void setAudiencia(Audiencia audiencia) {
        this.audiencia = audiencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_testigo")
    public Testigo getTestigo() {
        return this.testigo;
    }
    
    public void setTestigo(Testigo testigo) {
        this.testigo = testigo;
    }




}


