package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Testigosubaudiencia generated by hbm2java
 */
@Entity
@Table(name="testigosubaudiencia"
    ,schema="public"
)
public class Testigosubaudiencia  implements java.io.Serializable {


     private int idTestigosubaud;
     private Subaudiencia subaudiencia;
     private Testigo testigo;

    public Testigosubaudiencia() {
    }

	
    public Testigosubaudiencia(int idTestigosubaud) {
        this.idTestigosubaud = idTestigosubaud;
    }
    public Testigosubaudiencia(int idTestigosubaud, Subaudiencia subaudiencia, Testigo testigo) {
       this.idTestigosubaud = idTestigosubaud;
       this.subaudiencia = subaudiencia;
       this.testigo = testigo;
    }
   
     @Id 

    
    @Column(name="id_testigosubaud", unique=true, nullable=false)
    public int getIdTestigosubaud() {
        return this.idTestigosubaud;
    }
    
    public void setIdTestigosubaud(int idTestigosubaud) {
        this.idTestigosubaud = idTestigosubaud;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_subaudiencia")
    public Subaudiencia getSubaudiencia() {
        return this.subaudiencia;
    }
    
    public void setSubaudiencia(Subaudiencia subaudiencia) {
        this.subaudiencia = subaudiencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_testigo")
    public Testigo getTestigo() {
        return this.testigo;
    }
    
    public void setTestigo(Testigo testigo) {
        this.testigo = testigo;
    }




}


