package com.ars.sirproj.dto;
// Generated 26-feb-2014 12:16:25 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Titular generated by hbm2java
 */
@Entity
@Table(name="titular"
    ,schema="public"
)
public class Titular  implements java.io.Serializable {


     private int idTitular;
     private Juzgado juzgado;

    public Titular() {
    }

	
    public Titular(int idTitular) {
        this.idTitular = idTitular;
    }
    public Titular(int idTitular, Juzgado juzgado) {
       this.idTitular = idTitular;
       this.juzgado = juzgado;
    }
   
     @Id 

    
    @Column(name="id_titular", unique=true, nullable=false)
    public int getIdTitular() {
        return this.idTitular;
    }
    
    public void setIdTitular(int idTitular) {
        this.idTitular = idTitular;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_juzgado")
    public Juzgado getJuzgado() {
        return this.juzgado;
    }
    
    public void setJuzgado(Juzgado juzgado) {
        this.juzgado = juzgado;
    }




}


